### ISSUE TITLE
Criação de página sobre

### ISSUE THREAD

**Issue by cgonzaga** [cgonzaga2022/github-main#3]
Vocês poderiam criar uma página de sobre? Agradeço

**Comment by cgonzaga** [comment]
A página está em construção.

**Comment by cgonzaga2022** [comment]
Obrigado! Estou aguardando ...
________________________________
De: Carlos Gonzaga ***@***.***>
Enviado: sexta-feira, 30 de dezembro de 2022 22:06
Para: cgonzaga2022/github-main ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [cgonzaga2022/github-main] Criação de página sobre (Issue #3)


Vocês poderiam criar uma página de sobre? Agradeço
